### ISSUE TITLE
CSDN密码忘记了,作者思维很棒, 学习中

### ISSUE THREAD

**Issue by kleen** [Arronlong/httpclientUtil#1]
CSDN密码忘记了,思维很棒, 学习中  。 

1、登陆之后，如何得到cookie , 下次请求如何带入cookie

**Comment by Arronlong** [comment]
刚在代码中更新了测试类，同时也在csdn博客中补充了一篇携带Cookie的请求http://blog.csdn.net/xiaoxian8023/article/details/50474987

**Comment by kleen** [comment]
好人. 我拿什么来爱你。

**Comment by kleen** [comment]
谢谢. 1024
