### ISSUE TITLE
调用delete传参有示例吗，这样写是否可行？

### ISSUE THREAD

**Issue by walteryin** [Arronlong/httpclientUtil#10]
Header[] headers=HttpHeader.custom().userAgent("Mozilla/5.0")
				.contentType(Headers.APP_FORM_URLENCODED).build();  
		HttpConfig config = HttpConfig.custom().headers(headers).url(“https://localhost/message/template.json?appid=12993&signature=a3fcb88e97894ca0674b5a00480f3aa6&template_id=gK0hk2”).encoding("utf-8");
		String res = HttpClientUtil.send(config.method(HttpMethods.DELETE));
		System.out.println(res);

**Comment by Arronlong** [comment]
没有例子，不过这些都比较简单，我刚试了一下，没有问题。
同时，推荐你使用delete方法代替send方法。如：
<pre>String res = HttpClientUtil.delete(HttpConfig.custom().url(url));</pre>

**Comment by walteryin** [comment]
遇到的是一个比较奇葩的API，调用delete参数还只能放在报文体里面，只能变通一下
@NotThreadSafe
public class HttpDeleteWithBody extends HttpEntityEnclosingRequestBase {
    public static final String METHOD_NAME = "DELETE";
    public String getMethod() { return METHOD_NAME; }

    public HttpDeleteWithBody(final String uri) {
        super();
        setURI(URI.create(uri));
    }
    public HttpDeleteWithBody(final URI uri) {
        super();
        setURI(uri);
    }
    public HttpDeleteWithBody() { super(); }
}

**Comment by Arronlong** [comment]
那这个api就可以直接用get或者post方式请求，只要参数里面有method_name值为delete即可~可以通过map传值：
`
		map.put("METHOD_NAME ", "DELETE");
		HttpConfig config = HttpConfig.custom().url(url).map(map);
		String res = HttpClientUtil.post(config);
`
或者String方式传值：
`
		map.put(Utils.ENTITY_STRING, "METHOD_NAME=DELETE");
		config = HttpConfig.custom().url(url).map(map);
		String res = HttpClientUtil.post(config);
`
