### ISSUE TITLE
简单看了一下封装的代码块 发现全是同步执行 没有异步的封装么

### ISSUE THREAD

**Issue by xiaolongyuan** [Arronlong/httpclientutil#12]

**Comment by Lixianshengchao** [comment]
为什么要同步执行，我开启多个线程，导致实际上只有一个线程在执行

**Comment by Arronlong** [comment]
首先，以前的版本有异步，后来嫌麻烦，暂时去掉了，后续有时间了再合进来。
其次，test包有线程池和多线程的测试，测试一下你就知道是不是多线程

**Comment by Arronlong** [comment]
首先，以前的版本有异步，后来嫌麻烦，暂时去掉了，后续有时间了再合进来。
其次，test包有线程池和多线程的测试，测试一下你就知道是不是多线程
