### ISSUE TITLE
发现了一些问题

### ISSUE THREAD

**Issue by Lixianshengchao** [Arronlong/httpclientutil#18]
1 SSLs认证使用同步锁，导致开启多个线程实际上只有一个线程在执行。
解决：public SSLConnectionSocketFactory getSSLCONNSF(SSLProtocolVersion sslpv)  取消同步锁
2 请求没设置超时时间。
解决：HttpClientUtil 类中 execute(HttpConfig config)增加超市时间
//创建请求对象
			HttpRequestBase request = getRequest(config.url(), config.method());
			request.setConfig(RequestConfig.custom().setCircularRedirectsAllowed(true).build());
			//设置header信息
			request.setHeaders(config.headers());
			request.setConfig(RequestConfig.custom().setConnectionRequestTimeout(5000).build());
			request.setConfig(RequestConfig.custom().setConnectTimeout(5000).build());

3 代理没设置正确

HCB 类设置代理添加 setProxy(proxy)
    public HCB proxy(String hostOrIP, int port) {
        // 依次是代理地址，代理端口号，协议类型
        HttpHost proxy = new HttpHost(hostOrIP, port, "http");
        setProxy(proxy);
        DefaultProxyRoutePlanner routePlanner = new DefaultProxyRoutePlanner(proxy);
        return (HCB) this.setRoutePlanner(routePlanner);
    }

**Comment by Arronlong** [comment]
首先非常感谢提出的问题。下面依次回答一下：
1. getSSLCONNSF的返回值是一个工厂，并不是创建连接的时候使用了同步锁；
2. 超时时间可以在HCB中进行设置，即如果想自定义超时时间，需要先构建HttpClient对象
3. 代理的问题，不同的httpclient提供了多种设置方法，工具类中的方式是参考了官方文档，链接：http://hc.apache.org/httpcomponents-client-4.5.x/tutorial/html/connmgmt.html#d5e485
