### ISSUE TITLE
get请求是不可以传参数的吗

### ISSUE THREAD

**Issue by ABNER-1** [Arronlong/httpclientutil#19]
get请求是不是不可以传入参数，是直接构造包含参数的url吗

**Comment by xiexb** [comment]
com.arronlong.httpclientutil 包中
private static HttpResponse execute(HttpConfig config)的
if (HttpEntityEnclosingRequestBase.class.isAssignableFrom(request.getClass()))

**Comment by Arronlong** [comment]
@ABNER-1 get的确是直接在url后面拼装的~
 @xiexb 代码中没有问题
