### ISSUE TITLE
请问如何禁止自动重定向

### ISSUE THREAD

**Issue by CNdarkmoon** [Arronlong/httpclientutil#24]
没有找到具体的设置方法

**Comment by Arronlong** [comment]
参考HCB中的timeout方法：
`
	/**
	 * 设置超时时间以及是否允许网页重定向（自动跳转 302）
	 * 
	 * @param timeout		超时时间，单位-毫秒
	 * @param redirectEnable		自动跳转
	 * @return	返回当前对象
	 */
	public HCB timeout(int timeout,  boolean redirectEnable){
		// 配置请求的超时设置
		RequestConfig config = RequestConfig.custom()
				.setConnectionRequestTimeout(timeout)
				.setConnectTimeout(timeout)
				.setSocketTimeout(timeout)
				.setRedirectsEnabled(redirectEnable)
				.build();
		return (HCB) this.setDefaultRequestConfig(config);
	}
`
