### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by kleen** [Arronlong/httpclientUtil#3]
http://www.gao4.com/page3/b  
重定向
System.out.println(HttpClientUtil.send("http://www.gao4.com/page3/b"));

**Comment by kleen** [comment]
无解,尝试过N多办法,麻烦解决下

**Comment by kleen** [comment]
? 请问如何解决这个问题。

**Comment by Arronlong** [comment]
这样操作是可以的：
System.out.println(HttpClientUtil.get("http://www.gao4.com/page3/b",null,"gbk"));

**Comment by kleen** [comment]
谢谢， 一直都是使用 post 方式 ..
