### ISSUE TITLE
关于用json请求后一段时间内再次请求form请求，map中可能会带上这个$ENTITY_JSON$的json对象

### ISSUE THREAD

**Issue by qjwhnry** [Arronlong/httpclientUtil#30]
$ENTITY_JSON$={"ID":"58","URL":"http://123"}
请求的map通过config.map()打印出来，会存在$ENTITY_JSON$这个key值

**Comment by Landy941201** [comment]
我现在也遇到了这样的问题，我的请求中并没有设置$ENTITY_JSON$，但是请求会带上之前的一些数据

**Comment by qjwhnry** [comment]
1.0.4 有些bug，封装的代码中使用ThreadLocal这个变量保存key，会发现，当在一个线程请求了两次接口，就会出现这个问题，1.0.0版本是没问题的； 建议换用apache的。 不过注意最后的 io的close();

**Comment by Arronlong** [comment]
link https://github.com/Arronlong/httpclientutil/issues/38
