### ISSUE TITLE
这个jdk的版本是多少，我1.8不支持。

### ISSUE THREAD

**Issue by kleen** [Arronlong/httpclientUtil#5]
catch (KeyStoreException | NoSuchAlgorithmException| CertificateException | IOException | KeyManagementException e) {
			e.printStackTrace();
		}

**Comment by Arronlong** [comment]
额，这个JDK版本是1.7

**Comment by kleen** [comment]
改成1.8 吧, 我们不好同步 后续更新呢

**Comment by Arronlong** [comment]
好的，这两天就改动一下，最近任务比较多，你的另一个问题争取在这2天也看一下
