### ISSUE TITLE
这种请求通过 get 方式 报错。 

### ISSUE THREAD

**Issue by kleen** [Arronlong/httpclientUtil#9]
http://cron.qqe2.com/CalcRunTime.ashx?CronExpression=0/1 * * * * ?

Caused by: java.net.URISyntaxException: Illegal character in query at index 56: http://cron.qqe2.com/CalcRunTime.ashx?CronExpression=0/1 * * * * ?

**Comment by Arronlong** [comment]
刚实验了一下，只要将对参数进行url编码即可，或者直接将该地址在浏览器中打开，然后再从浏览器地址栏中复制出来，即为转码后的url。

我觉得这个问题，最好在调用工具类时，自己进行转码即可，无需在工具类里判断再转码。

`	public static void main(String[] args) throws HttpProcessException {
		String url = "http://cron.qqe2.com/CalcRunTime.ashx?CronExpression=0/1 * * * * ?";		
		String result = HttpClientUtil.get(HttpConfig.custom().url(url.replace(" ", "%20")));
		System.out.println(result);
	}
`

**Comment by Arronlong** [comment]
刚实验了一下，只要将对参数进行url编码即可，或者直接将该地址在浏览器中打开，然后再从浏览器地址栏中复制出来，即为转码后的url。

我觉得这个问题，最好在调用工具类时，自己进行转码即可，无需在工具类里判断再转码。

<pre>
	public static void main(String[] args) throws HttpProcessException {
		String url = "http://cron.qqe2.com/CalcRunTime.ashx?CronExpression=0/1 * * * * ?";		
		String result = HttpClientUtil.get(HttpConfig.custom().url(url.replace(" ", "%20")));
		System.out.println(result);
	}
</pre>
